language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "iojs"
before_install:
  - npm install
  - npm install istanbul -g
script: 
  - npm test
  - npm run-script cover
  - coveralls < ./coverage/lcov.info || true 
  
sudo: false
